

export const NEXT_PUBLIC_HOST_URL = process.env.NEXT_PUBLIC_HOST_URL
export const RESERVOIR_API_KEY = process.env.RESERVOIR_API_KEY
export const NEXT_PUBLIC_RESERVOIR_API_KEY = process.env.NEXT_PUBLIC_RESERVOIR_API_KEY
export const NEXT_PUBLIC_ALCHEMY_ID = process.env.NEXT_PUBLIC_ALCHEMY_ID || ''



export const NEXT_PUBLIC_NORMALIZE_ROYALTIES = process.env.NEXT_PUBLIC_NORMALIZE_ROYALTIES
export const NEXT_PUBLIC_DATADOG_APPLICATION_ID = process.env.NEXT_PUBLIC_DATADOG_APPLICATION_ID
export const NEXT_PUBLIC_DATADOG_CLIENT_TOKEN = process.env.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN
export const NEXT_PUBLIC_MARKETPLACE_SOURCE = process.env.NEXT_PUBLIC_MARKETPLACE_SOURCE
export const NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID || ''



export const NEXT_PUBLIC_POSTHOG_CLIENT_TOKEN = process.env.NEXT_PUBLIC_POSTHOG_CLIENT_TOKEN
export const NODE_ENV = process.env.NODE_ENV
export const NEXT_PUBLIC_SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN
export const NEXT_PUBLIC_MARKETPLACE_FEE = process.env.NEXT_PUBLIC_MARKETPLACE_FEE
export const ALLOWED_API_DOMAINS = process.env.ALLOWED_API_DOMAINS
export const NEXT_PUBLIC_RESERVOIR_WEBSOCKET_KEY = process.env.NEXT_PUBLIC_RESERVOIR_WEBSOCKET_KEY
export const NEXT_PUBLIC_RESERVOIR_BASE_URL = process.env.NEXT_PUBLIC_RESERVOIR_BASE_URL
export const NEXT_PUBLIC_REFERRER = process.env.NEXT_PUBLIC_REFERRER















//================= COMMUNITY =================


export const NEXT_PUBLIC_POLYGON_ZKEVM_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_POLYGON_ZKEVM_COLLECTION_SET_ID
export const NEXT_PUBLIC_POLYGON_ZKEVM_COMMUNITY = process.env.NEXT_PUBLIC_POLYGON_ZKEVM_COMMUNITY

export const NEXT_PUBLIC_POLYGON_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_POLYGON_COLLECTION_SET_ID
export const NEXT_PUBLIC_POLYGON_COMMUNITY = process.env.NEXT_PUBLIC_POLYGON_COMMUNITY

export const NEXT_PUBLIC_GOERLI_COMMUNITY = process.env.NEXT_PUBLIC_GOERLI_COMMUNITY


export const NEXT_PUBLIC_ETH_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_ETH_COLLECTION_SET_ID
export const NEXT_PUBLIC_ETH_COMMUNITY = process.env.NEXT_PUBLIC_ETH_COMMUNITY

export const NEXT_PUBLIC_SEPOLIA_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_SEPOLIA_COLLECTION_SET_ID
export const NEXT_PUBLIC_SEPOLIA_COMMUNITY = process.env.NEXT_PUBLIC_SEPOLIA_COMMUNITY

export const NEXT_PUBLIC_ARBITRUM_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_ARBITRUM_COLLECTION_SET_ID
export const NEXT_PUBLIC_ARBITRUM_COMMUNITY = process.env.NEXT_PUBLIC_ARBITRUM_COMMUNITY

export const NEXT_PUBLIC_ARBITRUM_NOVA_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_ARBITRUM_NOVA_COLLECTION_SET_ID
export const NEXT_PUBLIC_ARBITRUM_NOVA_COMMUNITY = process.env.NEXT_PUBLIC_ARBITRUM_NOVA_COMMUNITY


export const NEXT_PUBLIC_OPTIMISM_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_OPTIMISM_COLLECTION_SET_ID
export const NEXT_PUBLIC_OPTIMISM_COMMUNITY = process.env.NEXT_PUBLIC_OPTIMISM_COMMUNITY

export const NEXT_PUBLIC_BSC_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_BSC_COLLECTION_SET_ID
export const NEXT_PUBLIC_BSC_COMMUNITY = process.env.NEXT_PUBLIC_BSC_COMMUNITY

export const NEXT_PUBLIC_BASE_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_BASE_COLLECTION_SET_ID
export const NEXT_PUBLIC_BASE_COMMUNITY = process.env.NEXT_PUBLIC_BASE_COMMUNITY

export const NEXT_PUBLIC_LINEA_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_LINEA_COLLECTION_SET_ID
export const NEXT_PUBLIC_LINEA_COMMUNITY = process.env.NEXT_PUBLIC_LINEA_COMMUNITY


export const NEXT_PUBLIC_AVALANCHE_COLLECTION_SET_ID = process.env.NEXT_PUBLIC_AVALANCHE_COLLECTION_SET_ID
export const NEXT_PUBLIC_AVALANCHE_COMMUNITY = process.env.NEXT_PUBLIC_AVALANCHE_COMMUNITY
